fix build

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -142,10 +142,6 @@ jobs:
     runs-on: ${{ matrix.settings.host }}
     steps:
       - uses: actions/checkout@v3
-      - uses: jirutka/setup-alpine@v1
-        if: ${{ matrix.settings.arch }}
-        with:
-          arch: ${{ matrix.settings.arch }}
       - uses: pnpm/action-setup@v2
         name: Install pnpm
         with:
@@ -179,66 +175,94 @@ jobs:
           name: bindings-${{ matrix.settings.target }}
           path: ${{ env.APP_NAME }}.*.node
           if-no-files-found: error
+  # build-arm-musl:
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       settings:
+  #         - target: aarch64-unknown-linux-musl
+  #           arch: aarch64
+  #   name: ${{ matrix.settings.target }}
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - uses: actions/checkout@v3
+  #     - uses: jirutka/setup-alpine@v1
+  #       with:
+  #         arch: ${{ matrix.settings.arch }}
+  #         volumes: ~/.cargo:~/.cargo
+  #     - name: Cache cargo
+  #       uses: actions/cache@v3
+  #       with:
+  #         path: |
+  #           ~/.cargo/registry/index/
+  #           ~/.cargo/registry/cache/
+  #           ~/.cargo/git/db/
+  #           .cargo-cache
+  #           target/
+  #         key: ${{ matrix.settings.target }}-cargo-ubuntu-latest
+  #     - name: Build
+  #       shell: alpine.sh --root {0}
+  #       run: |-
+  #         set -e &&
+  #         apk update &&
+  #         apk add curl git gcc g++ make cmake gfortran libffi-dev openssl-dev autoconf automake libtool libuuid libevdev-dev xdo xdotool-dev libc-dev pkgconfig glib-dev gtk+3.0-dev pango-dev cairo-dev fontconfig-dev nodejs npm &&
+  #         curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh /dev/stdin -y &&
+  #         source $HOME/.cargo/env &&
+  #         rustup install nightly &&
+  #         rustup default nightly &&
+  #         rustup target add ${{ matrix.settings.target }} &&
+  #         npm install &&
+  #         PKG_CONFIG_SYSROOT_DIR=/ CARGO_BUILD_TARGET=${{ matrix.settings.target }} npm run build &&
+  #         strip *.node
+  #     - name: Upload artifact
+  #       uses: actions/upload-artifact@v3
+  #       with:
+  #         name: bindings-${{ matrix.settings.target }}
+  #         path: ${{ env.APP_NAME }}.*.node
+  #         if-no-files-found: error
+
   build-arm-musl:
-    strategy:
-      fail-fast: false
-      matrix:
-        settings:
-          - target: aarch64-unknown-linux-musl
-            arch: aarch64
-    name: ${{ matrix.settings.target }}
+    name: aarch64-unknown-linux-musl
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
-      - uses: jirutka/setup-alpine@v1
+      - uses: uraimo/run-on-arch-action@v2
+        name: Build artifact
         with:
-          arch: ${{ matrix.settings.arch }}
-          volumes: ~/.cargo:~/.cargo
-      - name: Cache cargo
-        uses: actions/cache@v3
-        with:
-          path: |
-            ~/.cargo/registry/index/
-            ~/.cargo/registry/cache/
-            ~/.cargo/git/db/
-            .cargo-cache
-            target/
-          key: ${{ matrix.settings.target }}-cargo-ubuntu-latest
-      - name: Build
-        shell: alpine.sh --root {0}
-        run: |-
-          set -e &&
-          apk update &&
-          apk add curl git gcc g++ make cmake gfortran libffi-dev openssl-dev autoconf automake libtool libuuid libevdev-dev xdo xdotool-dev libc-dev pkgconfig glib-dev gtk+3.0-dev pango-dev cairo-dev fontconfig-dev nodejs npm &&
-          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh /dev/stdin -y &&
-          source $HOME/.cargo/env &&
-          rustup install nightly &&
-          rustup default nightly &&
-          rustup target add ${{ matrix.settings.target }} &&
-          npm install &&
-          PKG_CONFIG_SYSROOT_DIR=/ CARGO_BUILD_TARGET=${{ matrix.settings.target }} npm run build &&
-          strip *.node
+          arch: aarch64
+          distro: alpine_latest
+          githubToken: ${{ github.token }}
+          dockerRunArgs: |
+            --volume "${PWD}:/addon"
+            --volume "~/.cargo:/root/.cargo"
+          install: |
+              apk update &&
+              apk add curl git gcc g++ make cmake gfortran libffi-dev openssl-dev autoconf automake libtool libuuid libevdev-dev xdo xdotool-dev libc-dev pkgconfig glib-dev gtk+3.0-dev pango-dev cairo-dev fontconfig-dev nodejs npm &&
+              curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh /dev/stdin -y &&
+              source $HOME/.cargo/env &&
+              rustup install nightly &&
+              rustup default nightly &&
+              rustup target add aarch64-unknown-linux-musl &&
+              npm install n -g &&
+              n stable &&
+          run: |
+              set -e &&
+              cd /addon &&
+              npm install &&
+              PKG_CONFIG_SYSROOT_DIR=/ CARGO_BUILD_TARGET=aarch64-unknown-linux-musl npm run build &&
+              strip *.node
       - name: Upload artifact
         uses: actions/upload-artifact@v3
         with:
-          name: bindings-${{ matrix.settings.target }}
+          name: aarch64-unknown-linux-musl
           path: ${{ env.APP_NAME }}.*.node
           if-no-files-found: error
+
   build-arm-gnu:
     name: aarch64-unknown-linux-gnu
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
-      - name: Cache cargo
-        uses: actions/cache@v3
-        with:
-          path: |
-            ~/.cargo/registry/index/
-            ~/.cargo/registry/cache/
-            ~/.cargo/git/db/
-            .cargo-cache
-            target/
-          key: aarch64-unknown-linux-gnu-cargo-ubuntu-latest
       - uses: uraimo/run-on-arch-action@v2
         name: Build artifact
         with:
@@ -248,8 +272,7 @@ jobs:
           dockerRunArgs: |
             --volume "${PWD}:/addon"
             --volume "~/.cargo:/root/.cargo"
-          run: |
-              set -e &&
+          install: |
               apt-get update &&
               apt-get install nodejs npm libxdo-dev uuid-dev libc-dev pkg-config libglib2.0-dev libgtk-3-dev libgtk2.0-dev libpango1.0-dev libcairo2-dev libfontconfig1-dev -y &&
               npm install n -g &&
@@ -259,6 +282,8 @@ jobs:
               rustup install nightly &&
               rustup default nightly &&
               rustup target add aarch64-unknown-linux-gnu &&
+          run: |
+              set -e &&
               cd /addon &&
               npm install &&
               PKG_CONFIG_SYSROOT_DIR=/ CARGO_BUILD_TARGET=aarch64-unknown-linux-gnu npm run build &&
@@ -293,9 +318,6 @@ jobs:
         with:
           name: bindings-aarch64-apple-darwin
           path: artifacts
-      - name: List packages
-        run: ls -R ./
-        shell: bash
       - name: Combine binaries
         run: pnpm universal
       - name: Upload artifact
